=== TrivadisPF/trivadis-technology-radar/validation/radar-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "The root schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": {},
    "examples": [
        {
            "title": "Angular",
            "info": "a modern web framework",
            "ring": "adopt",
            "quadrant": "languages-and-frameworks",
            "skills": "angular",
            "relatedTo": [],
            "alternativeTo": [],
            "skillsNeeded": [],
            "supportsTvdBB": [],
            "owners": [],
            "status": "draft",
            "featured": true,
            "__content": "\n\n[Angular](https://angular.io/) s a TypeScript-based open-source web application framework led by the Angular Team at Google and by a community of individuals and corporations. Angular is a complete rewrite from the same team that built AngularJS. \n\n"
        }
    ],
    "required": [
        "id",
        "title",
        "ring",
        "quadrant",
        "owners" 
    ],
    "properties": {
        "id": {
            "$id": "#/properties/id",
            "type": "string",
            "title": "The id schema",
            "description": "The id of the technology in lowercase.",
            "default": "",
            "examples": [
                "angualar"
            ]
        },
        "title": {
            "$id": "#/properties/title",
            "type": "string",
            "title": "The title schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "Angular"
            ]
        },
        "info": {
            "$id": "#/properties/info",
            "type": "string",
            "title": "The info schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "a modern web framework"
            ]
        },
        "ring": {
            "$id": "#/properties/ring",
            "type": "string",
            "title": "The ring schema",
            "enum": ["trial", "assess", "adopt", "hold", "watch"],
            "description": "An explanation about the purpose of this instance.",
            "default": "watch",
            "examples": [
                "adopt"
            ]
        },
        "quadrant": {
            "$id": "#/properties/quadrant",
            "type": "string",
            "title": "The quadrant schema",
            "enum": ["languages-and-frameworks", "data-management", "platforms-and-services", "architecture-methods-and-patterns"],
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "languages-and-frameworks"
            ]
        },
        "skills": {
            "$id": "#/properties/skills",
            "type": "string",
            "title": "The skills schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "angular"
            ]
        },
        "relatedTo": {
            "$id": "#/properties/relatedTo",
            "type": "array",
            "title": "The relatedTo schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                []
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/relatedTo/items"
            }
        },
        "alternativeTo": {
            "$id": "#/properties/alternativeTo",
            "type": "array",
            "title": "The alternativeTo schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                []
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/alternativeTo/items"
            }
        },
        "skillsNeeded": {
            "$id": "#/properties/skillsNeeded",
            "type": "array",
            "title": "The skillsNeeded schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                []
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/skillsNeeded/items"
            }
        },
        "supportsTvdBB": {
            "$id": "#/properties/supportsTvdBB",
            "type": "array",
            "title": "The supportsTvdBB schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                []
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/supportsTvdBB/items"
            }
        },
        "owners": {
            "$id": "#/properties/owners",
            "type": "array",
            "title": "The owners schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                []
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/owners/items"
            }
        },
        "status": {
            "$id": "#/properties/status",
            "type": "string",
            "title": "The status schema",
            "enum": ["draft","proposed","rejected","accepted","deprecated"],
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "draft"
            ]
        },
        "featured": {
            "$id": "#/properties/featured",
            "type": "boolean",
            "title": "The featured schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false,
            "examples": [
                true
            ]
        },
        "__content": {
            "$id": "#/properties/__content",
            "type": "string",
            "title": "The __content schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false
        }        
    },
    "additionalProperties": false
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2019-07-01/orchestration-driven-service-oriented-architecture.md.json
{
  "id": "orchestration-soa",
  "title": "Orchestration-Driven Service-Oriented Architecture",
  "ring": "hold",
  "quadrant": "architecture-methods-and-patterns",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\nJava"
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2019-07-01/service-based-architecture.md.json
{
  "id": "service-based-arch",
  "title": "Service-Based Architecture",
  "ring": "adopt",
  "quadrant": "architecture-methods-and-patterns",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\nJava"
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2019-07-01/platys.md.json
{
  "id": "platys",
  "title": "Platys",
  "ring": "trial",
  "quadrant": "languages-and-frameworks",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\n[platys](github.com/platys) is a tool developed by Trivadis for generating and provisioning Modern Data Platforms based on Docker and Docker Compose.\n"
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2019-07-01/tableau.md.json
{
  "id": "tableau",
  "title": "Tableau",
  "ring": "adopt",
  "quadrant": "platforms-and-services",
  "relatedTo": [],
  "alternativeTo": [
    "power-bi",
    "superset",
    "redas"
  ],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\n[Tableau](https://www.tableau.com/) query relational databases, online analytical processing cubes, cloud databases, and spreadsheets to generate graph-type data visualizations. The products can also extract, store, and retrieve data from an in-memory data engine."
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2021-01-15/microsoft-sqlserver.md.json
{
  "id": "sqlserver",
  "title": "Microsoft SQL Server",
  "ring": "adopt",
  "quadrant": "data-management",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\nOracle Database is a very popular relational database management system.\n"
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2020-12-31/great-expectations.md.json
{
  "id": "great-expectations",
  "title": "Great Expectations",
  "ring": "watch",
  "quadrant": "languages-and-frameworks",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\n[Great Expectations](https://greatexpectations.io/) helps data teams eliminate pipeline debt, through data testing, documentation, and profiling.\n"
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2020-07-29/influxdb.md.json
{
  "id": "influxdb",
  "title": "InfluxDB",
  "ring": "assess",
  "quadrant": "data-management",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\n[InfluxDB](https://www.influxdata.com/products/influxdb-overview/) is a native time series database designed to handle high write and query loads."
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2020-07-29/apache-atlas.md.json
{
  "id": "atlas",
  "title": "Apache Atlas",
  "ring": "assess",
  "quadrant": "platforms-and-services",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\n[Apache Atlas](https://atlas.apache.org/#/) is a Data Catalog.Atlas is a scalable and extensible set of core foundational governance services â€“ enabling enterprises to effectively and efficiently meet their compliance requirements within Hadoop and allows integration with the whole enterprise data ecosystem.\n"
}
