=== TrivadisPF/trivadis-technology-radar/validation/radar-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "The root schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": {},
    "examples": [
        {
            "title": "Angular",
            "info": "a modern web framework",
            "ring": "adopt",
            "quadrant": "languages-and-frameworks",
            "skills": "angular",
            "relatedTo": [],
            "alternativeTo": [],
            "skillsNeeded": [],
            "supportsTvdBB": [],
            "owners": [],
            "status": "draft",
            "featured": true,
            "__content": "\n\n[Angular](https://angular.io/) s a TypeScript-based open-source web application framework led by the Angular Team at Google and by a community of individuals and corporations. Angular is a complete rewrite from the same team that built AngularJS. \n\n"
        }
    ],
    "required": [
        "id",
        "title",
        "ring",
        "quadrant",
        "owners" 
    ],
    "properties": {
        "id": {
            "$id": "#/properties/id",
            "type": "string",
            "title": "The id schema",
            "description": "The id of the technology in lowercase.",
            "default": "",
            "examples": [
                "angualar"
            ]
        },
        "title": {
            "$id": "#/properties/title",
            "type": "string",
            "title": "The title schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "Angular"
            ]
        },
        "info": {
            "$id": "#/properties/info",
            "type": "string",
            "title": "The info schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "a modern web framework"
            ]
        },
        "ring": {
            "$id": "#/properties/ring",
            "type": "string",
            "title": "The ring schema",
            "enum": ["trial", "assess", "adopt", "hold", "watch"],
            "description": "An explanation about the purpose of this instance.",
            "default": "watch",
            "examples": [
                "adopt"
            ]
        },
        "quadrant": {
            "$id": "#/properties/quadrant",
            "type": "string",
            "title": "The quadrant schema",
            "enum": ["languages-and-frameworks", "data-management", "platforms-and-services", "architecture-methods-and-patterns"],
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "languages-and-frameworks"
            ]
        },
        "skills": {
            "$id": "#/properties/skills",
            "type": "string",
            "title": "The skills schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "angular"
            ]
        },
        "relatedTo": {
            "$id": "#/properties/relatedTo",
            "type": "array",
            "title": "The relatedTo schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                []
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/relatedTo/items"
            }
        },
        "alternativeTo": {
            "$id": "#/properties/alternativeTo",
            "type": "array",
            "title": "The alternativeTo schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                []
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/alternativeTo/items"
            }
        },
        "skillsNeeded": {
            "$id": "#/properties/skillsNeeded",
            "type": "array",
            "title": "The skillsNeeded schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                []
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/skillsNeeded/items"
            }
        },
        "supportsTvdBB": {
            "$id": "#/properties/supportsTvdBB",
            "type": "array",
            "title": "The supportsTvdBB schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                []
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/supportsTvdBB/items"
            }
        },
        "owners": {
            "$id": "#/properties/owners",
            "type": "array",
            "title": "The owners schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                []
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/owners/items"
            }
        },
        "status": {
            "$id": "#/properties/status",
            "type": "string",
            "title": "The status schema",
            "enum": ["draft","proposed","rejected","accepted","deprecated"],
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "draft"
            ]
        },
        "featured": {
            "$id": "#/properties/featured",
            "type": "boolean",
            "title": "The featured schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false,
            "examples": [
                true
            ]
        },
        "__content": {
            "$id": "#/properties/__content",
            "type": "string",
            "title": "The __content schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false
        }        
    },
    "additionalProperties": false
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2020-07-29/apache-airflow.md.json
{
  "id": "airflow",
  "title": "Apache Airflow",
  "ring": "trial",
  "quadrant": "platforms-and-services",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\n[Apache Airflow](https://airflow.apache.org/) is a platform created by the community to programmatically author, schedule and monitor workflows."
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2020-12-31/H2OWave.md.json
{
  "id": "h2o-wave",
  "title": "H2O Wave",
  "ring": "watch",
  "quadrant": "languages-and-frameworks",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\n[H2O Wave](https://h2oai.github.io/wave/) is a software stack for building beautiful, low-latency, realtime, browser-based applications and dashboards entirely in Python without using HTML, Javascript, or CSS."
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2019-07-01/mongodb.md.json
{
  "id": "mongodb",
  "title": "MongoDB",
  "ring": "adopt",
  "quadrant": "data-management",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\nMongoDB is a cross-platform document-oriented database program. Classified as a NoSQL database program, MongoDB uses JSON-like documents with schema. MongoDB is developed by MongoDB Inc. and licensed under the Server Side Public License (SSPL)."
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2019-07-01/react.md.json
{
  "id": "react",
  "title": "React",
  "ring": "adopt",
  "quadrant": "languages-and-frameworks",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\n[React](https://reactjs.org/) (also known as React.js or ReactJS) is an open-source JavaScript library for building user interfaces. It is maintained by Facebook and a community of individual developers and companies. React can be used as a base in the development of single-page or mobile applications. "
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2019-07-01/streamsets-datacollector.md.json
{
  "id": "streamsets",
  "title": "StreamSets Data Collector",
  "ring": "adopt",
  "quadrant": "platforms-and-services",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\nStreamSets Data Collector....\n"
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2020-12-31/dvc.md.json
{
  "id": "dvc",
  "title": "DVC",
  "ring": "watch",
  "quadrant": "languages-and-frameworks",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\n[DVC](https://dvc.org/) is built to make ML models shareable and reproducible. It is designed to handle large files, data sets, machine learning models, and metrics as well as code."
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2019-07-01/docker.md.json
{
  "id": "docker",
  "title": "Docker",
  "ring": "adopt",
  "quadrant": "platforms-and-services",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\n[Docker](https://www.docker.com/) is a set of platform as a service (PaaS) products that use OS-level virtualization to deliver software in packages called containers. Containers are isolated from one another and bundle their own software, libraries and configuration files; they can communicate with each other through well-defined channels."
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2020-07-29/apache-iceberg.md.json
{
  "id": "iceberg",
  "title": "Apache Iceberg",
  "ring": "assess",
  "quadrant": "languages-and-frameworks",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\n[Apache Iceberg](https://iceberg.apache.org/) is an open table format for huge analytic datasets. Iceberg adds tables to Presto and Spark that use a high-performance format that works just like a SQL table.\n\nApache Hudi would be interesting to try out as an alternative to [Delta Lake](../languages-and-frameworks/delta-lake.html) and [Apache Hudi](../languages-and-frameworks/apache-hudi.html). \n\nApache Iceberg is interesting as it is the favourite of [Dremio](../languages-and-frameworks/dremio.html) and will soon be supported by [Presto](../languages-and-frameworks/presto.html)."
}
