=== TrivadisPF/trivadis-technology-radar/validation/radar-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "The root schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": {},
    "examples": [
        {
            "title": "Angular",
            "info": "a modern web framework",
            "ring": "adopt",
            "quadrant": "languages-and-frameworks",
            "skills": "angular",
            "relatedTo": [],
            "alternativeTo": [],
            "skillsNeeded": [],
            "supportsTvdBB": [],
            "owners": [],
            "status": "draft",
            "featured": true,
            "__content": "\n\n[Angular](https://angular.io/) s a TypeScript-based open-source web application framework led by the Angular Team at Google and by a community of individuals and corporations. Angular is a complete rewrite from the same team that built AngularJS. \n\n"
        }
    ],
    "required": [
        "id",
        "title",
        "ring",
        "quadrant",
        "owners" 
    ],
    "properties": {
        "id": {
            "$id": "#/properties/id",
            "type": "string",
            "title": "The id schema",
            "description": "The id of the technology in lowercase.",
            "default": "",
            "examples": [
                "angualar"
            ]
        },
        "title": {
            "$id": "#/properties/title",
            "type": "string",
            "title": "The title schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "Angular"
            ]
        },
        "info": {
            "$id": "#/properties/info",
            "type": "string",
            "title": "The info schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "a modern web framework"
            ]
        },
        "ring": {
            "$id": "#/properties/ring",
            "type": "string",
            "title": "The ring schema",
            "enum": ["trial", "assess", "adopt", "hold", "watch"],
            "description": "An explanation about the purpose of this instance.",
            "default": "watch",
            "examples": [
                "adopt"
            ]
        },
        "quadrant": {
            "$id": "#/properties/quadrant",
            "type": "string",
            "title": "The quadrant schema",
            "enum": ["languages-and-frameworks", "data-management", "platforms-and-services", "architecture-methods-and-patterns"],
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "languages-and-frameworks"
            ]
        },
        "skills": {
            "$id": "#/properties/skills",
            "type": "string",
            "title": "The skills schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "angular"
            ]
        },
        "relatedTo": {
            "$id": "#/properties/relatedTo",
            "type": "array",
            "title": "The relatedTo schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                []
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/relatedTo/items"
            }
        },
        "alternativeTo": {
            "$id": "#/properties/alternativeTo",
            "type": "array",
            "title": "The alternativeTo schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                []
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/alternativeTo/items"
            }
        },
        "skillsNeeded": {
            "$id": "#/properties/skillsNeeded",
            "type": "array",
            "title": "The skillsNeeded schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                []
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/skillsNeeded/items"
            }
        },
        "supportsTvdBB": {
            "$id": "#/properties/supportsTvdBB",
            "type": "array",
            "title": "The supportsTvdBB schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                []
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/supportsTvdBB/items"
            }
        },
        "owners": {
            "$id": "#/properties/owners",
            "type": "array",
            "title": "The owners schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                []
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/owners/items"
            }
        },
        "status": {
            "$id": "#/properties/status",
            "type": "string",
            "title": "The status schema",
            "enum": ["draft","proposed","rejected","accepted","deprecated"],
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "draft"
            ]
        },
        "featured": {
            "$id": "#/properties/featured",
            "type": "boolean",
            "title": "The featured schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false,
            "examples": [
                true
            ]
        },
        "__content": {
            "$id": "#/properties/__content",
            "type": "string",
            "title": "The __content schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false
        }        
    },
    "additionalProperties": false
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2020-07-29/apache-pulsar.md.json
{
  "id": "pulsar",
  "title": "Apache Pulsar",
  "ring": "watch",
  "quadrant": "platforms-and-services",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\n[Apache Pulsar](https://pulsar.apache.org/) is an open-source distributed pub-sub messaging system originally created at Yahoo and now part of the Apache Software Foundation.\n\nIt has some features which are not (yet) available in Apache Kafka and therefore it is worth to have a look at Apache Pulsar."
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2019-07-01/kubernetes.md.json
{
  "id": "kubernetes",
  "title": "Kubernetes",
  "ring": "adopt",
  "quadrant": "platforms-and-services",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\nKubernetes is an open-source system for automating deployment, scaling and management of containerized applications that was originally designed by Google and now maintained by the Cloud Native Computing Foundation. It aims to provide a \"platform for automating deployment, scaling, and operations of application containers across clusters of hosts\". It works with a range of container tools, including Docker."
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2020-07-29/nextflow.md.json
{
  "id": "nextflow",
  "title": "Nextflow",
  "ring": "watch",
  "quadrant": "platforms-and-services",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\n[Nextflow](https://www.nextflow.io/) enables scalable and reproducible scientific workflows using software containers. It allows the adaptation of pipelines written in the most common scripting languages. \n\nts fluent DSL simplifies the implementation and the deployment of complex parallel and reactive workflows on clouds and clusters. "
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2019-07-01/angular.md.json
{
  "id": "angular",
  "title": "Angular",
  "info": "a modern web framework",
  "ring": "adopt",
  "quadrant": "languages-and-frameworks",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\n[Angular](https://angular.io/) s a TypeScript-based open-source web application framework led by the Angular Team at Google and by a community of individuals and corporations. Angular is a complete rewrite from the same team that built AngularJS. \n\n"
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2019-07-01/microsoft-dynamics-365.md.json
{
  "id": "dynamics",
  "title": "Microsoft Dynamics 365",
  "ring": "adopt",
  "quadrant": "platforms-and-services",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\n[Microsoft Dynamic 365](https://dynamics.microsoft.com/en-us/) empowers teamwork with dynamic and productive team sites for every project team, department, and division. Share files, data, news, and resources. Customize your site to streamline your teamâ€™s work. Collaborate effortlessly and securely with team members inside and outside your organization, across PCs, Macs, and mobile devices. "
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2019-07-01/microsoft-power-apps.md.json
{
  "id": "power-apps",
  "title": "Microsoft Power Apps",
  "ring": "adopt",
  "quadrant": "platforms-and-services",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\n[Microsoft Power Apps](https://powerapps.microsoft.com/en-us/) is a suite of apps, services, connectors and data platform that provides a rapid application development environment to build custom apps for your business needs. Using Power Apps, you can quickly build custom business apps that connect to your business data stored either in the underlying data platform (Common Data Service) or in various online and on-premises data sources (SharePoint, Excel, Office 365, Dynamics 365, SQL Server, and so on)."
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2020-12-31/trino.md.json
{
  "id": "trino",
  "title": "Trino",
  "ring": "watch",
  "quadrant": "platforms-and-services",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\n[Trino](https://trino.io/) is a distributed SQL query engine designed to query large data sets distributed over one or more heterogeneous data sources.\n\nTrino was previously named PrestoSQL but due to a competing fork of Presto called PrestoDB, the project has been renamed to Trino in December 2020."
}

=== TrivadisPF/trivadis-technology-radar/deployment/data-transfer/radar/json/radar/2021-01-15/oracle-directory-services.md.json
{
  "id": "oracle-directory-service",
  "title": "Oracle Directory Services",
  "ring": "adopt",
  "quadrant": "platforms-and-services",
  "relatedTo": [],
  "alternativeTo": [],
  "skillsNeeded": [],
  "supportsTvdBB": [],
  "owners": [],
  "status": "draft",
  "featured": true,
  "__content": "\n\nOracle Internet Directory and Oracle Unified Directory..."
}
